resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:47d87129d967a5f9d947915b414931e6ba7d42be45186123b531d760b93c6306
  name: controller
  newName: ghcr.io/mellanox/maintenance-operator
