---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-maintenance-nvidia-com-v1alpha1-nodemaintenance
  failurePolicy: Fail
  name: vnodemaintenance.kb.io
  rules:
  - apiGroups:
    - maintenance.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - nodemaintenances
  sideEffects: None
