# permissions for end users to view maintenanceoperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: maintenanceoperatorconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: maintenance-operator
    app.kubernetes.io/part-of: maintenance-operator
    app.kubernetes.io/managed-by: kustomize
  name: maintenanceoperatorconfig-viewer-role
rules:
- apiGroups:
  - maintenance.nvidia.com
  resources:
  - maintenanceoperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maintenance.nvidia.com
  resources:
  - maintenanceoperatorconfigs/status
  verbs:
  - get
