---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - maintenance.nvidia.com
  resources:
  - nodemaintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.nvidia.com
  resources:
  - nodemaintenances/finalizers
  verbs:
  - update
- apiGroups:
  - maintenance.nvidia.com
  resources:
  - nodemaintenances/status
  verbs:
  - get
  - patch
  - update
