apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: maintenance-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeMaintenance is the Schema for the nodemaintenances API
      displayName: Node Maintenance
      kind: NodeMaintenance
      name: nodemaintenances.maintenance.nvidia.com
      version: v1alpha1
  description: Coordinates And Performs Common Node Preparations For Maintenance
  displayName: NVIDIA Maintenance Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - node
  - maintenance
  - drain
  links:
  - name: Maintenance Operator
    url: https://maintenance-operator.domain
  maintainers:
  - email: noemail@nodomain.com
    name: na
  maturity: alpha
  minKubeVersion: 1.30.0
  provider:
    name: Nvidia
  version: 0.0.0
