name: "Build, Test, Lint"
on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-ci-reusable.yml@main
    with:
      coverage-file: cover.out
      validate-command: |
        go mod tidy
        git diff --exit-code
        make generate
        make manifests
        git diff --exit-code
  build-image:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/image-build-reusable.yml@main
    with:
      build-args: GOPROXY=https://proxy.golang.org,direct
  e2e-test:
    runs-on: ubuntu-24.04
    needs: [ci, build-image]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: prepare test k8s cluster
        run: make test-env-e2e
      - name: build and deploy operator
        run: make deploy-operator-e2e
      - name: run e2e tests
        run: make test-e2e
      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e-test-artifacts
          path: ./artifacts
      - name: cleanup
        if: always()
        run: make clean-test-env-e2e
